### ISSUE TITLE
Upgrade from travis-ci legacy platform

### ISSUE THREAD

**Issue by SevereOverfl0w** [carrot/roots-css-pipeline#12]
http://docs.travis-ci.com/user/migrating-from-legacy/

From what I've seen, we'll have no problem migrating to their new platform. I think we should just do it!

**Comment by jenius** [comment]
Absolutely. I've done this for a number of other projects, just havent got to this one yet. It's a one line change, feel free to PR this in and I'll merge right away :grinning:
