### ISSUE TITLE
Possibility of using Sass instead of Stylus

### ISSUE THREAD

**Issue by BenjaminRCooper** [carrot/roots-css-pipeline#15]
Just wondered if this was to be added, or already existed and I've just missed it?

**Comment by FranzSkuffka** [comment]
It is possible. I think you can just install Sass through npm and add your configuration to the `app.coffee`. Check out [accord](https://github.com/jenius/accord) for further information.

**Comment by jenius** [comment]
Yep, just install `node-sass` and change the file extension to `.scss` or `.sass` and everything will work perfectly fine :grinning:
