### ISSUE TITLE
Output inline css instead of <link...

### ISSUE THREAD

**Issue by marcinant** [carrot/roots-css-pipeline#18]
Is this possible to embed minified css in <style> tag instead of <link>?

I would like to optimize performance and inline some critical above-the-fold css.

**Comment by jenius** [comment]
If you submitted a PR that added an option to output the straight css in a `<style>` tag instead of as an external stylesheet I'd definitely take a look!

**Comment by marcinant** [comment]
Thank you for your quick response, however actually I changed my mind in this topic.

Inline css should be supported on import, though better option is to make css inline **after** compilation.

Perfect workflow IMHO is:

jade/pug/whatever -> html + scss -> css => uncss -> cssnano => inline css

The above work flow is implemented in Google _web-starter-kit_ and I have to admit that this is better solution.

**Comment by jenius** [comment]
Ok cool, good luck then!
