### ISSUE TITLE
Css file being created - but empty

### ISSUE THREAD

**Issue by lb-** [carrot/roots-css-pipeline#20]
Hi, I am having trouble with bootstrap, I have installed it via npm, it is loaded into the modules, i have figured out how to get the js file imported but stuck on the css.

I have tried both the .css and the .scss file, I have tried building out to a file and just letting it run as default.

Each time I end up with the file loaded/created but it it is just a blank (empty) file.

Below is an excerpt from my app.coffee file

app.coffee

```
extensions: [
   //browserify etc
   css_pipeline(files: './node_modules/bootstrap/dist/css/bootstrap.min.css', out: 'css/build.css', minify: true),
]
```

Versions: Roots 5.0.0, css-pipeline 3.1.0, bootstrap ^4.0.0-alpha.2

Full fules on gitlab repo
package.json https://gitlab.com/lb-/personal-website/blob/master/package.json
app.coffee https://gitlab.com/lb-/personal-website/blob/master/app.coffee

**Comment by jescalan** [comment]
Have you tried moving the bootstrap file to somewhere other than the `node_modules` folder and loading it from there? See if you can narrow down the issue just a little bit more here 😁

**Comment by lb-** [comment]
Hi, thanks for the response, obviously accessing via node_modules is not the best way but I really was hoping for a non-copying solution but that works for now so going with it. issue closed.

thanks for the response :)
